# Generated by Django 5.2 on 2025-05-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_client_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ("name",)},
        ),
    ]
